project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "MFR"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: outreach.qmd
        text: Outreach

format:
  html:
    theme: cosmo
    css: ./assets/css/custom.css
    toc: true

editor: visual

